build:
  image: node:6
  commands:
    - npm i -g yarn
    - yarn install
    - yarn lint
    - yarn build
    - yarn install --production

publish:
  docker:
    registry: $$DOCKER_REGISTRY
    username: $$DOCKER_LOGIN
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: ephyros/app
    tag: latest
    file: Dockerfile
    when:
      branch: master
  docker:
    registry: $$DOCKER_REGISTRY
    username: $$DOCKER_LOGIN
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: ephyros/web
    tag: latest
    file: nginx/Dockerfile
    when:
      branch: master

deploy:
  rancher:
    image: zxbodya/drone-rancher
    url: $$RANCHER_URL
    access_key: $$RANCHER_KEY
    secret_key: $$RANCHER_SECRET
    service: ephyros/app
    docker_image: $$DOCKER_REGISTRY/ephyros/app:latest
    confirm: true
    when:
      branch: master
  rancher:
    image: zxbodya/drone-rancher
    url: $$RANCHER_URL
    access_key: $$RANCHER_KEY
    secret_key: $$RANCHER_SECRET
    service: ephyros/web
    docker_image: $$DOCKER_REGISTRY/ephyros/web:latest
    confirm: true
    when:
      branch: master
# deploy:
#   ssh:
#     host: ephyros.com
#     user: root
#     port: 22
#     commands:
#       - cd ephyros.com
#       - docker-compose pull
#       - docker-compose up -d
