cache:
  mount:
    - /drone/npm-cache
    - /drone/nm_dev
    - node_modules

build:
  image: node:5
  commands:
    - npm config set cache /drone/npm-cache --global
    - mv node_modules /drone/nm_prod || true
    - mv /drone/nm_dev ./node_modules || true
    - npm install
    - npm run lint
    - npm run build
    - mv node_modules /drone/nm_dev
    - mv /drone/nm_prod ./node_modules || true
    - npm install --production
    - npm prune --production

publish:
  docker:
    registry: $$DOCKER_REGISTRY
    username: $$DOCKER_LOGIN
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: ephyros/app
    tag: latest
    file: Dockerfile
    when:
      branch: master
  docker:
    registry: $$DOCKER_REGISTRY
    username: $$DOCKER_LOGIN
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: ephyros/web
    tag: latest
    file: nginx/Dockerfile
    when:
      branch: master

deploy:
  rancher:
    image: zxbodya/drone-rancher
    url: $$RANCHER_URL
    access_key: $$RANCHER_KEY
    secret_key: $$RANCHER_SECRET
    service: ephyros/app
    docker_image: $$DOCKER_REGISTRY/ephyros/app:latest
    confirm: true
    when:
      branch: master
  rancher:
    image: zxbodya/drone-rancher
    url: $$RANCHER_URL
    access_key: $$RANCHER_KEY
    secret_key: $$RANCHER_SECRET
    service: ephyros/web
    docker_image: $$DOCKER_REGISTRY/ephyros/web:latest
    confirm: true
    when:
      branch: master
# deploy:
#   ssh:
#     host: ephyros.com
#     user: root
#     port: 22
#     commands:
#       - cd ephyros.com
#       - docker-compose pull
#       - docker-compose up -d
