version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.9

    working_directory: ~/app

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # run tests!
      - run: yarn lint --quiet
      - run: yarn test
      # build
      - run: yarn build
      - setup_remote_docker:
          docker_layer_caching: true

      - run: |
         if [ "${CIRCLE_BRANCH}" == "master" ]; then

         docker login -u ${DOCKER_REGISTRY_USER} -p ${DOCKER_REGISTRY_PASSWORD} ${DOCKER_REGISTRY}

         docker build -t ${DOCKER_REGISTRY}/ephyros/app:latest -f Dockerfile .
         docker build -t ${DOCKER_REGISTRY}/ephyros/web:latest -f nginx/Dockerfile .

         docker push ${DOCKER_REGISTRY}/ephyros/app:latest
         docker push ${DOCKER_REGISTRY}/ephyros/web:latest

         fi
      - add_ssh_keys:
          fingerprints:
            - "a5:a7:e5:77:66:da:89:16:93:a0:b9:43:57:bb:53:a9"
      - run: ssh-keyscan -t rsa -H ephyros.com >> ~/.ssh/known_hosts
      - deploy:
          name: Deploy master to ephyros.com
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh ubuntu@ephyros.com "cd ephyros.com && ./update.sh"
            fi
